# Generated by Django 3.2.7 on 2021-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headfoot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_address_krd',
            options={'verbose_name': 'Краснодарский адрес', 'verbose_name_plural': 'Краснодарские адреса'},
        ),
        migrations.AlterModelOptions(
            name='footer_address_msk',
            options={'verbose_name': 'Московский адрес', 'verbose_name_plural': 'Московские адреса'},
        ),
        migrations.AlterModelOptions(
            name='footer_email',
            options={'verbose_name': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='header_phone',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterField(
            model_name='header_phone',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
