# Generated by Django 3.2.7 on 2021-10-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headfoot', '0002_auto_20211025_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header_phone',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
