# Generated by Django 3.2.7 on 2021-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoCRM', '0002_seothings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seothings',
            name='pageDescription',
            field=models.TextField(blank=True, help_text='длина до 450 символов, заполнять обязательно', max_length=450, verbose_name='SEO Описание страницы'),
        ),
        migrations.AlterField(
            model_name='seothings',
            name='pageTitle',
            field=models.CharField(blank=True, help_text='длина до 210 символов, заполнять обязательно', max_length=210, verbose_name='SEO Заголовок страницы'),
        ),
    ]
