# Generated by Django 3.2.7 on 2021-11-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoCRM', '0003_auto_20211108_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seoThings',
            new_name='amoSeoThings',
        ),
    ]
