# Generated by Django 3.2.7 on 2021-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoCRMpage_BasicTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicTermsTitle', models.CharField(max_length=255, verbose_name='Заголовок слева')),
                ('basicTermsMiniTitle', models.CharField(max_length=255, verbose_name='Маленький Заголовок справа')),
                ('basicTermsText1', models.TextField(max_length=255, verbose_name='Пункт 1 под правым заголовком')),
                ('basicTermsText2', models.TextField(max_length=255, verbose_name='Пункт 2 под правым заголовком')),
                ('basicTermsText3', models.TextField(max_length=255, verbose_name='Пункт 3 под правым заголовком')),
            ],
            options={
                'verbose_name': 'amoCRM | Второй экран',
                'verbose_name_plural': 'amoCRM | Второй экран',
            },
        ),
        migrations.AlterModelOptions(
            name='amocrmpage_bannerup',
            options={'verbose_name': 'amoCRM | Первый экран', 'verbose_name_plural': 'amoCRM | Первый экран'},
        ),
        migrations.AlterField(
            model_name='amocrmpage_bannerup',
            name='bannerUpImg',
            field=models.ImageField(upload_to='bannerimg/', verbose_name='Картинка Главного Баннера'),
        ),
    ]
