# Generated by Django 3.2.7 on 2021-10-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211025_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoCRMpage_CrmTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crmTypesTitle', models.CharField(max_length=255, verbose_name='Заголовок в центре')),
                ('crmTypesLeftMiniTitle', models.CharField(max_length=255, verbose_name='Маленький Заголовок слева')),
                ('crmTypesLeftText1', models.TextField(max_length=255, verbose_name='Пункт 1 под левым заголовком')),
                ('crmTypesLeftText2', models.TextField(max_length=255, verbose_name='Пункт 2 под левым заголовком')),
                ('crmTypesLeftText3', models.TextField(max_length=255, verbose_name='Пункт 3 под левым заголовком')),
                ('crmTypesRightMiniTitle', models.CharField(max_length=255, verbose_name='Маленький Заголовок справа')),
                ('crmTypesRightText1', models.TextField(max_length=255, verbose_name='Пункт 1 под правым заголовком')),
                ('crmTypesRightText2', models.TextField(max_length=255, verbose_name='Пункт 2 под правым заголовком')),
                ('crmTypesRightText3', models.TextField(max_length=255, verbose_name='Пункт 3 под правым заголовком')),
            ],
            options={
                'verbose_name': 'amoCRM | Третий экран',
                'verbose_name_plural': 'amoCRM | Третий экран',
            },
        ),
    ]
