# Generated by Django 3.2.7 on 2021-10-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_amocrmpage_crmtypes_crmtypesrighttext3'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoCRMpage_CrmAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crmAdvantagesImg', models.ImageField(upload_to='amopageimg/', verbose_name='Картинка слева от текста')),
                ('crmAdvantagesTitle', models.CharField(max_length=255, verbose_name='Заголовок в центре')),
                ('crmAdvantagesTitle1', models.CharField(max_length=255, verbose_name='Заголовок справа 1')),
                ('crmAdvantagesText1', models.TextField(max_length=255, verbose_name='Пункт 1 под правым заголовком')),
                ('crmAdvantagesText2', models.TextField(max_length=255, verbose_name='Пункт 2 под правым заголовком')),
                ('crmAdvantagesText3', models.TextField(max_length=255, verbose_name='Пункт 3 под правым заголовком')),
                ('crmAdvantagesText4', models.TextField(max_length=255, verbose_name='Пункт 4 под правым заголовком')),
                ('crmAdvantagesText5', models.TextField(max_length=255, verbose_name='Пункт 5 под правым заголовком')),
                ('crmAdvantagesText6', models.TextField(max_length=255, verbose_name='Пункт 6 под правым заголовком')),
                ('crmAdvantagesText7', models.TextField(max_length=255, verbose_name='Пункт 7 под правым заголовком')),
                ('crmAdvantagesTitle2', models.CharField(max_length=255, verbose_name='Заголовок справа 2')),
                ('crmAdvantagesTitle3', models.CharField(max_length=255, verbose_name='Заголовок справа 3')),
            ],
            options={
                'verbose_name': 'amoCRM | Четвертый экран',
                'verbose_name_plural': 'amoCRM | Четвертый экран',
            },
        ),
    ]
