# Generated by Django 3.2.7 on 2021-10-26 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_amocrmpage_crmadvantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesImg2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='amopageimg/', verbose_name='Картинка справа от текста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesImg3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='amopageimg/', verbose_name='Картинка слева от текста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTexRight2',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 2 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextLeft',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Текст под левым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Текст справа от заголовка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight1',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 1 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight3',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 3 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight4',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 4 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTitleLeft',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Заголовок слева'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTitleLeft2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Заголовок слева 2'),
            preserve_default=False,
        ),
    ]
