# Generated by Django 3.2.7 on 2021-10-26 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211026_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc1',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Подпункт 1 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc2',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Подпункт 2 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc3',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Подпункт 3 под правым заголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc4',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Подпункт 4 под правым заголовком'),
            preserve_default=False,
        ),
    ]
