# Generated by Django 3.2.7 on 2021-10-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20211026_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesImg3',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTexRight2',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight1',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight3',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRight4',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc1',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc2',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc3',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTextRightdesc4',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesTitleLeft2',
        ),
    ]
