# Generated by Django 3.2.7 on 2021-10-26 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20211026_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage3',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage4',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage5',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_crmadvantages',
            name='crmAdvantagesStage6',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Этап 6'),
            preserve_default=False,
        ),
    ]
