# Generated by Django 3.2.7 on 2021-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20211026_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoCRMpage_amo_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_priceTitle', models.CharField(max_length=255, verbose_name='Название тарифа amoCRM')),
                ('amo_priceDescription', models.CharField(max_length=255, verbose_name='Описание тарифа')),
                ('amo_priceText', models.TextField(max_length=255, verbose_name='Пункты тарифа')),
            ],
            options={
                'verbose_name': 'amoCRM | Экран с тарифами amoCRM',
                'verbose_name_plural': 'amoCRM | Экран с тарифами amoCRM',
            },
        ),
    ]
