# Generated by Django 3.2.7 on 2021-11-01 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_amocrmpage_amo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmpage_amo_price',
            name='amo_pricePrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Стоимость тарифа amoCRM'),
            preserve_default=False,
        ),
    ]
