# Generated by Django 3.2.7 on 2021-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20211101_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoCRMpage_amo_combo_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_combo_priceTitle', models.CharField(max_length=255, verbose_name='Название пакетного тарифа amoCRM')),
                ('amo_combo_priceDescription', models.CharField(max_length=255, verbose_name='Описание пакетного тарифа')),
                ('amo_combo_priceText1', models.TextField(max_length=255, verbose_name='Пункт 1 тарифа')),
                ('amo_combo_priceText2', models.TextField(max_length=255, verbose_name='Пункт 2 тарифа')),
                ('aamo_combo_pricePrice', models.CharField(max_length=255, verbose_name='Стоимость пакетного тарифа amoCRM')),
            ],
            options={
                'verbose_name': 'amoCRM | Экран с пакетными тарифами amoCRM',
                'verbose_name_plural': 'amoCRM | Экран с пакетными тарифами amoCRM',
            },
        ),
    ]
