# Generated by Django 3.2.7 on 2021-11-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_amocrmpage_amo_combo_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amocrmpage_amo_combo_price',
            old_name='aamo_combo_pricePrice',
            new_name='amo_combo_pricePrice',
        ),
    ]
