# Generated by Django 3.2.7 on 2021-11-02 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_amocrmpage_amo_implementation_price_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText10',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 10 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText11',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 11 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText12',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 12 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText13',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 13 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText14',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 14 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText15',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 15 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText16',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 16 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText17',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 17 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText8',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 8 тарифа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText9',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Пункт 9 тарифа'),
            preserve_default=False,
        ),
    ]
