# Generated by Django 3.2.7 on 2021-11-02 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20211102_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_pricePriceMsk',
        ),
        migrations.RemoveField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_pricePriceRegion',
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceDays',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Срок выполнения работ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_pricePrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Стоимость тарифа amoCRM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText15',
            field=models.TextField(max_length=555, verbose_name='Пункт 15 тарифа'),
        ),
        migrations.AlterField(
            model_name='amocrmpage_amo_implementation_price_first',
            name='amo_Implementation_priceText17',
            field=models.TextField(max_length=555, verbose_name='Пункт 17 тарифа'),
        ),
    ]
