# Generated by Django 3.2.7 on 2021-11-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_amocrmpage_amo_implementation_price_fourth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amoCRMpage_amo_combo_price',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_amo_Implementation_price_First',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_amo_Implementation_price_Fourth',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_amo_Implementation_price_Second',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_amo_Implementation_price_Third',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_amo_price',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_BannerUp',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_BasicTerms',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_CrmAdvantages',
        ),
        migrations.DeleteModel(
            name='amoCRMpage_CrmTypes',
        ),
    ]
