# Generated by Django 3.2.7 on 2021-11-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otel24page_BannerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(max_length=255, verbose_name='Заголовок Главного Экрана')),
            ],
            options={
                'verbose_name': 'Отель24 | Первый экран',
                'verbose_name_plural': 'Отель24 | Первый экран',
            },
        ),
    ]
