# Generated by Django 3.2.7 on 2021-11-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seoThings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(blank=True, help_text='длина до 210 символов, заполнять обязательно', max_length=210, verbose_name='SEO Заголовок страницы')),
                ('pageDescription', models.TextField(blank=True, help_text='длина до 450 символов, заполнять обязательно', max_length=450, verbose_name='SEO Описание страницы')),
            ],
            options={
                'verbose_name': 'SEO | Настройки',
                'verbose_name_plural': 'SEO | Настройки',
            },
        ),
    ]
