# Generated by Django 3.2.7 on 2021-11-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otel24', '0002_seothings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seoThings',
            new_name='otel24seoThings',
        ),
    ]
