# Generated by Django 3.2.7 on 2021-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel24', '0004_setuprateone'),
    ]

    operations = [
        migrations.CreateModel(
            name='setupRateTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setupRateTitle', models.CharField(max_length=255, verbose_name='Название тарифа внедрения Отель24')),
                ('setupRateText1', models.TextField(max_length=555, verbose_name='Пункт 1 тарифа')),
                ('setupRateText2', models.TextField(max_length=555, verbose_name='Пункт 2 тарифа')),
                ('setupRateText3', models.TextField(max_length=555, verbose_name='Пункт 3 тарифа')),
                ('setupRateText4', models.TextField(max_length=555, verbose_name='Пункт 4 тарифа')),
                ('setupRateText5', models.TextField(max_length=555, verbose_name='Пункт 5 тарифа')),
                ('setupRateText6', models.TextField(max_length=555, verbose_name='Пункт 6 тарифа')),
                ('setupRatePrice', models.CharField(max_length=255, verbose_name='Стоимость тарифа Отель24')),
                ('setupRateDays', models.CharField(max_length=255, verbose_name='Срок выполнения работ')),
            ],
            options={
                'verbose_name': 'Стоимость второго тарифа Отель24',
                'verbose_name_plural': 'Стоимость второго тарифа Отель24',
            },
        ),
    ]
