# Generated by Django 3.2.7 on 2021-11-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitrix24page_bannerup',
            name='bannerUpImg',
        ),
    ]
