# Generated by Django 3.2.7 on 2021-11-08 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0003_bitrix24page_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix24page_certificate',
            name='certificateTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Название Сертификата партнера Б24'),
            preserve_default=False,
        ),
    ]
